AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Contact-Keeper

  Application to save and manage events

Globals:
  Function:
    Timeout: 3
    MemorySize: 256

Resources:
  MyDatabaseSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: MyDatabaseSecret
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 16
        ExcludeCharacters: '"@/\\'

  MyDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: '8.0.35'
      MasterUsername: !Join [ '', [ '{{resolve:secretsmanager:', !Ref MyDatabaseSecret, ':SecretString:username}}' ] ]
      MasterUserPassword: !Join [ '', [ '{{resolve:secretsmanager:', !Ref MyDatabaseSecret, ':SecretString:password}}' ] ]
      DBName: contact_keeper

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'
        - PolicyName: SecretsManagerReadWrite
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'

  EventsApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: EventApi
      StageName: Prod

  UsersApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: UserApi
      StageName: Prod

  CreateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_management/
      Handler: app.create_user
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        CreateUser:
          Type: Api
          Properties:
            RestApiId: !Ref UsersApiGateway
            Path: /users
            Method: POST

  ReadUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_management/
      Handler: app.read_user
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        ReadUser:
          Type: Api
          Properties:
            RestApiId: !Ref UsersApiGateway
            Path: /users/{id}
            Method: GET

  UpdateUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_management/
      Handler: app.update_user
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        UpdateUser:
          Type: Api
          Properties:
            RestApiId: !Ref UsersApiGateway
            Path: /users/{id}
            Method: PUT

  DeleteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: user_management/
      Handler: app.delete_user
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        DeleteUser:
          Type: Api
          Properties:
            RestApiId: !Ref UsersApiGateway
            Path: /users/{id}
            Method: DELETE

  CreateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: events_management/
      Handler: app.create_event
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        CreateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /events
            Method: POST

  ReadEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: events_management/
      Handler: app.read_event
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        ReadEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /events/{id}
            Method: GET

  UpdateEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: events_management/
      Handler: app.update_event
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        UpdateEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /events/{id}
            Method: PUT

  DeleteEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: events_management/
      Handler: app.delete_event
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        DeleteEvent:
          Type: Api
          Properties:
            RestApiId: !Ref EventsApiGateway
            Path: /events/{id}
            Method: DELETE

Outputs:
  EventKeeperApi:
    Description: "API Gateway endpoint URL for Prod stage for Event Keeper functions"
    Value: !Sub "https://${EventsApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/contacts/"
  UserManagementApi:
    Description: "API Gateway endpoint URL for Prod stage for User Management functions"
    Value: !Sub "https://${UsersApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod/users/"
  CreateUserFunction:
    Description: "Create User Lambda Function ARN"
    Value: !GetAtt CreateUserFunction.Arn
  ReadUserFunction:
    Description: "Read User Lambda Function ARN"
    Value: !GetAtt ReadUserFunction.Arn
  UpdateUserFunction:
    Description: "Update User Lambda Function ARN"
    Value: !GetAtt UpdateUserFunction.Arn
  DeleteUserFunction:
    Description: "Delete User Lambda Function ARN"
    Value: !GetAtt DeleteUserFunction.Arn
  CreateEventFunction:
    Description: "Create Event Lambda Function ARN"
    Value: !GetAtt CreateEventFunction.Arn
  ReadEventFunction:
    Description: "Read Event Lambda Function ARN"
    Value: !GetAtt ReadEventFunction.Arn
  UpdateEventFunction:
    Description: "Update Event Lambda Function ARN"
    Value: !GetAtt UpdateEventFunction.Arn
  DeleteEventFunction:
    Description: "Delete Event Lambda Function ARN"
    Value: !GetAtt DeleteEventFunction.Arn
