name: CI/CD Workflow

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
      - name: Run tests
        run: python -m unittest discover tests

  sonarcloud:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: [test, sonarcloud]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      
      - name: Install SAM CLI
        run: pip install aws-sam-cli
      
      - name: Build SAM application
        run: |
          cd contact-Keeper
          sam build --use-container
      
      - name: Deploy SAM application
        run: |
          cd contact-Keeper
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name utez --capabilities CAPABILITY_IAM

  update_jira:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Jira Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      
      - name: Extract Jira issue key
        id: extract_jira_key
        run: |
          JIRA_KEY=$(echo "${{ github.event.head_commit.message }}" | grep -o '^[A-Z]*-[0-9]*')
          echo "JIRA_KEY=$JIRA_KEY" >> $GITHUB_OUTPUT
      
      - name: Update Jira
        if: steps.extract_jira_key.outputs.JIRA_KEY
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.extract_jira_key.outputs.JIRA_KEY }}
          transition: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' && 'Done' || github.ref == 'refs/heads/develop' && 'In Progress' || 'En revisión' }}
      
      - name: Add Jira comment
        if: steps.extract_jira_key.outputs.JIRA_KEY
        uses: atlassian/gajira-comment@master
        with:
          issue: ${{ steps.extract_jira_key.outputs.JIRA_KEY }}
          comment: |
            Actualización de GitHub:
            {panel}
            Repositorio: ${{ github.repository }}
            Branch: ${{ github.ref }}
            Commit: ${{ github.sha }}
            Autor: ${{ github.actor }}
            Evento: ${{ github.event_name }}
            {panel}
